#!/usr/bin/env bash

cmd <<<'mklink /D %homepath%\.ssh Z:\.ssh' >/dev/null
cmd <<<'mklink %homepath%\.bash_profile_default %homepath%\dotfiles\.bash_profile_default' >/dev/null

cat <<EOF >~/.bash_profile
# generated by ~/dotfiles/win-setup.sh
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

source ~/dotfiles/scripts/win/fix_docker.sh
# Workaround for Docker for Windows in Git Bash.
docker()
{
        (export MSYS_NO_PATHCONV=1; "docker.exe" "$@")
}
export PATH="$PATH:/c/Program Files/StaxRip/Apps/Encoders/ffmpeg"

EOF

cat <<EOF >~/.bashrc
# generated by ~/dotfiles/win-setup.sh
[[ $- == *i* ]] || return
source ~/.bash_profile_default
source ~/dotfiles/light-setup.sh
source ~/dotfiles/auto-ssh-agent.sh

EOF
